Few fixes for `pretty` feature

diff --git a/bashmount b/bashmount
--- a/bashmount
+++ b/bashmount
@@ -147,10 +147,10 @@ if (( colourize )); then
 fi
 
 msg() {
-    printf '\n%b\n\n' "${GREEN}${NOTE_ARROW}${ALL_OFF}${BOLD} ${*}${ALL_OFF}" >&2
+    printf '\n%b\n\n' "${GREEN}${ARROW}${ALL_OFF}${BOLD} ${*}${ALL_OFF}" >&2
 }
 error() {
-    printf '\n%b\n\n' "${RED}${NOTE_ARROW}${BOLD} ERROR: ${*}${ALL_OFF}" >&2
+    printf '\n%b\n\n' "${RED}${ARROW}${BOLD} ERROR: ${*}${ALL_OFF}" >&2
 }
 enter_to_continue() {
     printf '\n'
@@ -212,60 +212,58 @@ print_submenu_commands() {
     fi
 }
 
-UTF8_LINE='\xE2\x94\x81'
-UTF8_BRACKET_L='\xE2\x94\xA5'
-UTF8_BRACKET_R='\xE2\x94\x9D'
-NOTE_ARROW="==>"
+declare -r UTF8_LINE='━'
+declare -r UTF8_BRACKET_L='┥'
+declare -r UTF8_BRACKET_R='┝'
+declare -r ARROW="==>"
 
-if (( pretty )); then
-    utf_sed_expr="y/]-[/${UTF8_BRACKET_R}${UTF8_LINE}${UTF8_BRACKET_L}/"
-else
-    utf_sed_expr=''
-fi
-
-pretty_print() {
+__print() {
     printf "${BOLD}"
-    printf "%s\n\n" "${1}" | sed -e "${utf_sed_expr}"
+    if (( pretty )); then
+        printf '%s\n\n' "$1" \
+            | sed -e "y/]-[/${UTF8_BRACKET_R}${UTF8_LINE}${UTF8_BRACKET_L}/"
+    else
+        printf '%s\n\n' "$1"
+    fi
     printf "${ALL_OFF}"
 }
-
 print_separator() {
-    pretty_print '-----------------------------------------------------------------------------'
+    __print "-----------------------------------------------------------------------------"
 }
 print_separator_commands() {
-    pretty_print '--------------------------------[ Commands ]---------------------------------'
+    __print "--------------------------------[ Commands ]---------------------------------"
 }
 print_separator_device() {
-    pretty_print '-------------------------------[ Device Menu ]-------------------------------'
+    __print "-------------------------------[ Device Menu ]-------------------------------"
 }
 print_separator_optical() {
-    pretty_print '------------------------------[ Optical Media ]------------------------------'
+    __print "------------------------------[ Optical Media ]------------------------------"
 }
 print_separator_removable() {
-    pretty_print '-----------------------------[ Removable Media ]-----------------------------'
+    __print "-----------------------------[ Removable Media ]-----------------------------"
 }
 print_separator_internal() {
-    pretty_print '-----------------------------[ Internal Media ]------------------------------'
+    __print "-----------------------------[ Internal Media ]------------------------------"
 }
 
 print_help() {
     clear
     print_commands
     print_separator
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To mount the first device, enter ${ALL_OFF}"
     printf '%s' "${BLUE}1m${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To open the mountpath directory of the first${ALL_OFF}"
     printf '\n\n'
     printf '%s' "       ${BOLD}device (mounting if required), enter "
     printf '%s' "${BLUE}1o${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To view a device sub-menu, just enter the number.${ALL_OFF}"
     printf '\n\n'
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BLUE}[Enter]${ALL_OFF}"
     printf '%s' "${BOLD}, "
     printf '%s' "${BLUE}a${ALL_OFF}"
@@ -284,11 +282,11 @@ print_help_sub() {
     print_submenu_commands
     printf '\n'
     print_separator
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To perform a command, enter a character and press ${ALL_OFF}"
     printf '%s' "${BLUE}[Enter]${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}For example, to mount this device, type ${ALL_OFF}"
     printf '%s' "${BLUE}m${ALL_OFF} and press ${BLUE}[Enter]${ALL_OFF}"
     printf '%s' "${BOLD}.${ALL_OFF}"
