Fix behaviour of "udisks" variable. If udisks is set to "auto", determine "udisks" as '1' or '0'. If udisks is set to "1", exit with error if udisks is not available. Without this change, "auto" and "1" are the same. Shorten tests.

diff --git a/bashmount b/bashmount
--- a/bashmount
+++ b/bashmount
@@ -113,17 +113,16 @@ if [[ -f "${CONFIGFILE}" ]]; then
     fi
 fi
 
-if [[ "${udisks}" == "auto" ]] || (( udisks == 1 )); then
-    type -p udisksctl >/dev/null 2>&1
-    if (( $? != 0 )); then
-        udisks=0
-    else
-        udisks=1
+if [[ "${udisks}" == "auto" ]]; then
+    type -p udisksctl >/dev/null 2>&1 && udisks=1 || udisks=0
+elif  (( udisks == 1 )); then
+    if ! type -p udisksctl >/dev/null 2>&1; then
+        printf '%s\n' "bashmount: 'udisksctl': command not found"
+        exit 69
     fi
 fi
 
-type -p lsblk >/dev/null 2>&1
-if (( $? != 0 )); then
+if ! type -p lsblk >/dev/null 2>&1; then
     printf '%s\n' "bashmount: 'lsblk': command not found"
     exit 69
 fi
