New version

diff --git a/bashmount b/bashmount
--- a/bashmount
+++ b/bashmount
@@ -165,18 +165,20 @@ declare mount_options="${default_mount_options}"
 #         GENERAL FUNCTIONS           #
 #-------------------------------------#
 # {{{
-unset ALL_OFF BOLD BLUE GREEN RED
+unset ALL_OFF BOLD BLUE GREEN RED YELLOW
 if (( colourize )); then
     if tput setaf 0 >/dev/null 2>&1; then
         ALL_OFF="$(tput sgr0)"
         BOLD="$(tput bold)"
         BLUE="${BOLD}$(tput setaf 4)"
+	YELLOW="${BOLD}$(tput setaf 3)"
         GREEN="${BOLD}$(tput setaf 2)"
         RED="${BOLD}$(tput setaf 1)"
     else
         ALL_OFF='\e[1;0m'
         BOLD='\e[1;1m'
         BLUE="${BOLD}\e[1;34m"
+	YELLOW="${BOLD}\e[1;33m"
         GREEN="${BOLD}\e[1;32m"
         RED="${BOLD}\e[1;31m"
     fi
@@ -184,55 +186,91 @@ if (( colourize )); then
 fi
 
 msg() {
-    printf '%s\n' "${GREEN}==>${ALL_OFF}${BOLD} ${@}${ALL_OFF}" >&2
+    acprint ' ==> ' '' '' 'green' >&2
+    acprint "${@}" '' '' 'bold' >&2
+    printf '%s\n'
+    #printf '%s\n' "${GREEN}==>${ALL_OFF}${BOLD} ${@}${ALL_OFF}" >&2
 }
 
 error() {
-    printf '%s\n' "${RED}==>${ALL_OFF}${BOLD} ERROR: ${@}${ALL_OFF}" >&2
+    acprint ' ==> ' '' '' 'red' >&2
+    acprint "ERROR: ${@}" '' '' 'bold' >&2
+    printf '%s\n'
+    #printf '%s\n' "${RED}==>${ALL_OFF}${BOLD} ERROR: ${@}${ALL_OFF}" >&2
 }
 
 print_commands() {
     print_separator_commands
-    printf '%s' "${BLUE}*e${ALL_OFF}: eject ${BLUE}*i${ALL_OFF}: info"
-    printf '%s' " ${BLUE}*m${ALL_OFF}: mount   ${BLUE}*o${ALL_OFF}: open"
-    printf '%s\n' "  ${BLUE}*u${ALL_OFF}: unmount"
-    printf '%s' " ${BLUE}a${ALL_OFF}: unmount all"
-    printf '%s' "     ${BLUE}r${ALL_OFF}: refresh"
-    printf '%s\n\n' "  ${BLUE}q${ALL_OFF}: quit   ${BLUE}?${ALL_OFF}: help"
+    acprint '*e' '2' 'r' 'blue'; acprint ' eject' '12';
+    acprint '*i' '2' 'r' 'blue'; acprint ' info' '12';
+    acprint '*m' '2' 'r' 'blue'; acprint ' mount' '12';
+    printf '%s\n'
+    acprint '*o' '2' 'r' 'blue'; acprint ' open' '12';
+    acprint '*u' '2' 'r' 'blue'; acprint ' unmount' '12';
+    acprint  'a' '2' 'r' 'blue'; acprint ' unmount all' '12';
+    printf '%s\n'
+    acprint  'r' '2' 'r' 'blue'; acprint ' refresh' '12';
+    acprint  'q' '2' 'r' 'blue'; acprint ' quit' '12';
+    acprint  '?' '2' 'r' 'blue'; acprint ' help' '12';
+    printf '\n\n'
+    #printf '%s' "${BLUE}*e${ALL_OFF}: eject ${BLUE}*i${ALL_OFF}: info"
+    #printf '%s' " ${BLUE}*m${ALL_OFF}: mount   ${BLUE}*o${ALL_OFF}: open"
+    #printf '%s\n' "  ${BLUE}*u${ALL_OFF}: unmount"
+    #printf '%s' " ${BLUE}a${ALL_OFF}: unmount all"
+    #printf '%s' "     ${BLUE}r${ALL_OFF}: refresh"
+    #printf '%s\n\n' "  ${BLUE}q${ALL_OFF}: quit   ${BLUE}?${ALL_OFF}: help"
 }
 
 print_submenu_commands() {
     print_separator_commands
-    printf '%s' "${BLUE}e${ALL_OFF}: eject   ${BLUE}i${ALL_OFF}: info"
+    acprint 'e' '2' 'r' 'blue'; acprint ' eject' '12';
+    acprint 'i' '2' 'r' 'blue'; acprint ' info' '12';
+    
+#    printf '%s' "${BLUE}e${ALL_OFF}: eject   ${BLUE}i${ALL_OFF}: info"
     if info_mounted "${devname}"; then
-        printf '%s' "   ${BLUE}u${ALL_OFF}: unmount"
+	acprint 'u' '2' 'r' 'blue'; acprint ' unmount' '12';
+#	printf '%s' "   ${BLUE}u${ALL_OFF}: unmount"
     else
-        printf '%s' "   ${BLUE}m${ALL_OFF}: mount"
+	acprint 'u' '2' 'r' 'blue'; acprint ' mount' '12';
+#        printf '%s' "   ${BLUE}m${ALL_OFF}: mount"
     fi
-    printf '%s\n\n' "   ${BLUE}o${ALL_OFF}: open"
-    printf '%s' "${BLUE}b${ALL_OFF}: back   ${BLUE}r${ALL_OFF}: refresh"
-    printf '%s\n' "   ${BLUE}q${ALL_OFF}: quit   ${BLUE}?${ALL_OFF}: help"
+    printf '%s\n'
+    acprint 'o' '2' 'r' 'blue'; acprint ' open' '12';
+    acprint 'b' '2' 'r' 'blue'; acprint ' back' '12';
+    acprint 'r' '2' 'r' 'blue'; acprint ' refresh' '12';
+    printf '%s\n'
+    acprint '?' '2' 'r' 'blue'; acprint ' help' '12';
+    printf '%s\n'
+    acprint '1' '2' 'r' 'blue'; acprint ' read-only' '12';
+    acprint '2' '2' 'r' 'blue'; acprint ' luksOpen' '12';
+    acprint '3' '2' 'r' 'blue'; acprint ' luksClose' '12';
+#    printf '%s\n\n' "   ${BLUE}o${ALL_OFF}: open"
+#    printf '%s' "${BLUE}b${ALL_OFF}: back   ${BLUE}r${ALL_OFF}: refresh"
+#    printf '%s\n' "   ${BLUE}q${ALL_OFF}: quit   ${BLUE}?${ALL_OFF}: help"
 
-    printf '\n'
-    printf '%s' "${BLUE}1${ALL_OFF}: read-only"
-    printf '%s' "   ${BLUE}2${ALL_OFF}: luksOpen"
-    printf '%s' "   ${BLUE}3${ALL_OFF}: luksClose"
+#    printf '\n'
+#    printf '%s' "${BLUE}1${ALL_OFF}: read-only"
+#    printf '%s' "   ${BLUE}2${ALL_OFF}: luksOpen"
+#    printf '%s' "   ${BLUE}3${ALL_OFF}: luksClose"
     printf '\n'
 
-    if (( custom4_show )) || (( custom5_show )) || (( custom6_show )); then
-        printf '\n'
-    fi
+#    if (( custom4_show )) || (( custom5_show )) || (( custom6_show )); then
+#        printf '\n'
+#    fi
 
     if (( custom4_show )) && [[ -n "${custom4_desc}" ]]; then
-        printf '%s' "${BLUE}4${ALL_OFF}: ${custom4_desc}"
+        acprint '4' '2' 'r' 'blue'; acprint "${custom4_desc}" '12';
+#	printf '%s' "${BLUE}4${ALL_OFF}: ${custom4_desc}"
     fi
 
     if (( custom5_show )) && [[ -n "${custom5_desc}" ]]; then
-        printf '%s' "   ${BLUE}5${ALL_OFF}: ${custom5_desc}"
+        acprint '5' '2' 'r' 'blue'; acprint "${custom5_desc}" '12';
+#        printf '%s' "   ${BLUE}5${ALL_OFF}: ${custom5_desc}"
     fi
 
     if (( custom6_show )) && [[ -n "${custom6_desc}" ]]; then
-        printf '%s' "   ${BLUE}6${ALL_OFF}: ${custom6_desc}"
+        acprint '6' '2' 'r' 'blue'; acprint "${custom6_desc}" '12';
+#        printf '%s' "   ${BLUE}6${ALL_OFF}: ${custom6_desc}"
     fi
 
     if (( custom4_show )) || (( custom5_show )) || (( custom6_show )); then
@@ -252,26 +290,32 @@ invalid_command() {
 }
 
 print_separator() {
+#    printf '%s\n'
     printf '%s\n\n' '====================================================='
 }
 
 print_separator_commands() {
+#    printf '%s\n'
     printf '%s\n\n' '===================== COMMANDS ======================'
 }
 
 print_separator_device() {
+#    printf '%s\n'
     printf '%s\n\n' '==================== DEVICE MENU ===================='
 }
 
 print_separator_optical() {
+#    printf '%s\n'
     printf '%s\n\n' '=================== OPTICAL MEDIA ==================='
 }
 
 print_separator_removable() {
+#    printf '%s\n'
     printf '%s\n\n' '================== REMOVABLE MEDIA =================='
 }
 
 print_separator_internal() {
+#    printf '%s\n'
     printf '%s\n\n' '================== INTERNAL MEDIA ==================='
 }
 
@@ -339,31 +383,76 @@ print_device_name() {
     listed[device_number]="${devname}"
     (( device_number++ ))
 
-    printf '%s' " ${BLUE}${device_number})${ALL_OFF}"
+    acprint "${device_number})" '4' 'r' 'blue'
     devnameshort="${devname##*/}"
 
-    if (( !show_full_device_names )) && (( ${#devnameshort} > padding )); then
-        pre_length=$(( padding - post_length - 3 ))
-        devnamepre="${devnameshort:0:pre_length}"
-        devnamepost="${devnameshort:${#devnameshort}-post_length}"
-        devnameshort="${devnamepre}...${devnamepost}"
-    fi
+    # if (( !show_full_device_names )) && (( ${#devnameshort} > padding )); then
+    #     pre_length=$(( padding - post_length - 3 ))
+    #     devnamepre="${devnameshort:0:pre_length}"
+    #     devnamepost="${devnameshort:${#devnameshort}-post_length}"
+    #     devnameshort="${devnamepre}...${devnamepost}"
+    # fi
 
-    printf '%s' " ${devnameshort}:"
+    acprint " ${devnameshort}" '8'
+    # printf '%s' " ${devnameshort}:"
 
     # Add padding between device location and device label.
-    devname_length="${#devnameshort}"
-    for (( i=padding ; i>devname_length ; i-- )); do
-        printf '%s' " "
-    done
+    # devname_length="${#devnameshort}"
+    # for (( i=padding ; i>devname_length ; i-- )); do
+    #     printf '%s' " "
+    # done
 
-    printf '%s' " ${info_label}"
+    # printf '%s' " ${info_label}"
+    acprint "${info_label}" '14' 'l'
+    local device_size=$(info_size "${devname}")
+    acprint " ${device_size}" '7' 'l' 'yellow'
     if info_mounted "${devname}"; then
         path_mount="$(info_mountpath "${devname}")";
-        printf '%s' " ${GREEN}[$path_mount]${ALL_OFF}"
+        acprint " [$path_mount]" '22' 'l' 'green'
         mounted[${#mounted[*]}]="${devname}"
     fi
     printf '\n'
+}
+
+# $1 - string
+# $2 - length
+# $3 - align [r]
+# $4 - color/bold
+acprint() {
+    local post_length=6
+    case "${4}" in
+	'blue')  printf '%s' "${BLUE}"  ;;
+	'green') printf '%s' "${GREEN}" ;;
+	'yellow') printf '%s' "${YELLOW}";;
+	'red')   printf '%s' "${RED}"   ;;
+	'bold')  printf '%s' "${BOLD}"  ;;
+	*) ;;
+    esac
+    if [[ ! ${2} == "" ]]; then
+	local space=${2}-${#1};
+	if (( space < 0 )); then
+            pre_length=$(( ${2} - post_length - 3 ))
+            strpre="${1:0:pre_length}"
+            strpost="${1:${#1}-post_length}"
+            output="${strpre}...${strpost}";
+	else
+	    output="${1}"
+	fi
+
+	case "${3}" in
+            'r') for (( i=0 ; i<space ; i++ )) ; do
+		     printf '%s' " "
+    		 done
+		 printf '%s' "${output}";;
+            *)   printf '%s' "${output}"
+		 for (( i=0 ; i<space ; i++ )) ; do
+		     printf '%s' " "
+    		 done;;
+	esac
+    else
+	printf '%s' "${1}"
+    fi
+    if [[ ! ${4} == "" ]]; then printf '%s' "${ALL_OFF}"; fi
 }
 
 # }}}
