Unicode eye-candy with option to toggle

diff --git a/bashmount b/bashmount
--- a/bashmount
+++ b/bashmount
@@ -54,6 +54,7 @@ declare -i show_optical=1
 declare -i show_commands=1
 declare -i show_full_device_names=0
 declare -i colourize=1
+declare -i pretty=1
 declare -i custom4_show=0
 declare -i custom5_show=0
 declare -i custom6_show=0
@@ -146,10 +147,10 @@ if (( colourize )); then
 fi
 
 msg() {
-    printf '\n%s\n\n' "${GREEN}==>${ALL_OFF}${BOLD} ${*}${ALL_OFF}" >&2
+    printf '\n%b\n\n' "${GREEN}${NOTE_ARROW}${ALL_OFF}${BOLD} ${*}${ALL_OFF}" >&2
 }
 error() {
-    printf '\n%s\n\n' "${RED}==>${ALL_OFF}${BOLD} ERROR: ${*}${ALL_OFF}" >&2
+    printf '\n%b\n\n' "${RED}${NOTE_ARROW}${ALL_OFF}${BOLD} ERROR: ${*}${ALL_OFF}" >&2
 }
 enter_to_continue() {
     printf '\n'
@@ -211,43 +212,61 @@ print_submenu_commands() {
     fi
 }
 
+UTF8_LINE='\xE2\x94\x81'
+UTF8_BRACKET_L='\xE2\x94\xA5'
+UTF8_BRACKET_R='\xE2\x94\x9D'
+
+if (( pretty )); then
+    utf_sed_expr="y/]=[/${UTF8_BRACKET_R}${UTF8_LINE}${UTF8_BRACKET_L}/"
+    NOTE_ARROW="${BOLD}\xE2\x80\xA3${ALL_OFF}"
+else
+    utf_sed_expr=''
+    NOTE_ARROW="==>"
+fi
+
 print_separator() {
-    printf '%s\n\n' "-----------------------------------------------------------------------------"
+    printf "${BOLD}"
+    printf "%s\n\n" "${1}" | sed -e "${utf_sed_expr}"
+    printf "${ALL_OFF}"
+}
+
+print_separator_dumb() {
+    print_separator '============================================================================='
 }
 print_separator_commands() {
-    printf '%s\n\n' "--------------------------------- COMMANDS ----------------------------------"
+    print_separator '================================[ Commands ]================================='
 }
 print_separator_device() {
-    printf '%s\n\n' "-------------------------------- DEVICE MENU --------------------------------"
+    print_separator '===============================[ Device Menu ]==============================='
 }
 print_separator_optical() {
-    printf '%s\n\n' "------------------------------- OPTICAL MEDIA -------------------------------"
+    print_separator '==============================[ Optical Media ]=============================='
 }
 print_separator_removable() {
-    printf '%s\n\n' "------------------------------ REMOVABLE MEDIA ------------------------------"
+    print_separator '=============================[ Removable Media ]============================='
 }
 print_separator_internal() {
-    printf '%s\n\n' "------------------------------ INTERNAL MEDIA -------------------------------"
+    print_separator '=============================[ Internal Media ]=============================='
 }
 
 print_help() {
     clear
     print_commands
-    print_separator
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    print_separator_dumb
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To mount the first device, enter ${ALL_OFF}"
     printf '%s' "${BLUE}1m${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To open the mountpath directory of the first${ALL_OFF}"
     printf '\n\n'
     printf '%s' "       ${BOLD}device (mounting if required), enter "
     printf '%s' "${BLUE}1o${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To view a device sub-menu, just enter the number.${ALL_OFF}"
     printf '\n\n'
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BLUE}[Enter]${ALL_OFF}"
     printf '%s' "${BOLD}, "
     printf '%s' "${BLUE}a${ALL_OFF}"
@@ -257,7 +276,7 @@ print_help() {
     printf '%s' "${BLUE}?${ALL_OFF} "
     printf '%s' "${BOLD}do not require a number.${ALL_OFF}"
     printf '\n\n'
-    print_separator
+    print_separator_dumb
     enter_to_continue
 }
 
@@ -265,17 +284,17 @@ print_help_sub() {
     clear
     print_submenu_commands
     printf '\n'
-    print_separator
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    print_separator_dumb
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}To perform a command, enter a character and press ${ALL_OFF}"
     printf '%s' "${BLUE}[Enter]${ALL_OFF}${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    printf '%s' "  ${GREEN}==>${ALL_OFF}  "
+    printf '%b' "  ${GREEN}${NOTE_ARROW}${ALL_OFF}  "
     printf '%s' "${BOLD}For example, to mount this device, type ${ALL_OFF}"
     printf '%s' "${BLUE}m${ALL_OFF} and press ${BLUE}[Enter]${ALL_OFF}"
     printf '%s' "${BOLD}.${ALL_OFF}"
     printf '\n\n'
-    print_separator
+    print_separator_dumb
     enter_to_continue
 }
 
@@ -639,7 +658,7 @@ submenu() {
         print_submenu_commands
     fi
     printf '\n'
-    print_separator
+    print_separator_dumb
 
     # Receive user input.
     local -i retval
@@ -719,7 +738,7 @@ submenu() {
 select_action() {
     local devname
     local letter
-    print_separator
+    print_separator_dumb
     read -r -e -p "Command: " action
     if [[ "$action" =~ ^[1-9] ]]; then
         if [[ "$action" =~ ^[1-9][0-9]*$ ]]; then
